import { AWS_S3_URL } from '../../constants'

export const images = [
  { src: AWS_S3_URL + "partners/bbc.png" },
  { src: AWS_S3_URL + "partners/business.png" },
  { src: AWS_S3_URL + "partners/buy.png" },
  { src: AWS_S3_URL + "partners/calvinayre.png" },
  { src: AWS_S3_URL + "partners/daily_mail.png" },
  { src: AWS_S3_URL + "partners/douthlondon.png" },
  { src: AWS_S3_URL + "partners/eastate.png" },
  { src: AWS_S3_URL + "partners/eugaming.png" },
  { src: AWS_S3_URL + "partners/evening.png" },
  { src: AWS_S3_URL + "partners/findmy.png" },
  { src: AWS_S3_URL + "partners/houseb.png" },
  { src: AWS_S3_URL + "partners/inside.png" },
  { src: AWS_S3_URL + "partners/metro.png" },
  { src: AWS_S3_URL + "partners/mirror.png" },
  { src: AWS_S3_URL + "partners/moneymagpie.png" },
  { src: AWS_S3_URL + "partners/portal_watch.png" },
  { src: AWS_S3_URL + "partners/quax.png" },
  { src: AWS_S3_URL + "partners/sundat_express.png" },
  { src: AWS_S3_URL + "partners/the_assisted.png" },
  { src: AWS_S3_URL + "partners/the_sun.png" },
  { src: AWS_S3_URL + "partners/the_telegraph.png" },
  { src: AWS_S3_URL + "partners/this_is_money.png" },
  { src: AWS_S3_URL + "partners/ukf.png" },
  { src: AWS_S3_URL + "partners/which.png" },
  { src: AWS_S3_URL + "partners/mylondon.png" },
];
